# Generated by Django 3.2.2 on 2021-06-20 17:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None), blank=True, null=True, size=None)),
                ('board_length', models.IntegerField(choices=[(8, 'Short'), (10, 'Long')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('is_ended', models.BooleanField(default=False)),
                ('is_full', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, max_length=2, related_name='players', to=settings.AUTH_USER_MODEL)),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='queue', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Checkers Board',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0), size=None), size=None)),
                ('step', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None)),
                ('step_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=1)),
                ('game_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='checkers.gameboard')),
                ('step_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Checkers Histories',
                'ordering': ['order'],
                'unique_together': {('game_board', 'order')},
            },
        ),
    ]
